language: rust
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdbus-1-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    # Rustfmt
    - env: RUSTFMT_VERSION="0.7.0"
      rust: nightly-2018-05-24
      install:
        - rustup component add rustfmt-preview
        - cargo install rustfmt-nightly --force --version $RUSTFMT_VERSION || echo "rustfmt already installed"
      before_script:
        - cargo-fmt fmt -- --version
      script:
        - cargo fmt -- --check
