language: rust
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdbus-1-dev
rust:
  - stable
script:
  - cargo fmt -- --check
  - touch ./src/main.rs && cargo clippy -- -D warnings
  - cargo test
